version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: onlinechat_postgres
    restart: always
    environment:
      POSTGRES_DB: OnlineChat_DB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

